import { IntegrationDataObject } from "@/app/interfaces";

export const integrationsData:IntegrationDataObject[] = [
    {
        name:"quickbooks",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/w5G98LJ5sghVLaDJ8Aziv6lZKYOdRBJTQ1eOlcjv.png",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/X0p5ld0TwyzDavKthcaHKsvwzuQ8HDeXnOXIe78z.svg",
        link:"/integrations/quickbooks"
    },
    {
        name:"xero",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/I9xEb9XWK7PQm7X6OZdP4i3PG6tjwtopggDrjmXX.png",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/zw6ZIVEY0fNKHNLqxZ2doAENvbgb2Z1rkpgCHM2c.svg",
        link:"/integrations/quickbooks"
    },
    {
        name:"zapier",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/xtgy3eakIHa7LayJxzICZpMl4G1XtutKYvCyWCQa.jpg",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/hQmlUm8MOBFFZva6eTCKbywZQFcwqKV7Sbx1854o.svg",
        link:"/integrations/quickbooks"
    },
    {
        name:"IFTTT",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/wM72Z4rNr6sE3J63Q1yLYGP7RnECM4GA2Z3Juwq3.jpg",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/JYfBCm1FueVL1bdPyUhcuTNi9lbtPK6ElV0l1AGr.svg",
        link:"/integrations/quickbooks"
    },
    {
        name:"hubspot",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/Nr9FNGkb65jUe2b0FB5fHWBCvRRsybZGWQUB71f0.webp",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/KZGE1v3n0ei7POaGfBaEmnNki33QwRF3XTEVj04c.svg",
        link:"/integrations/quickbooks"
    },
    {
        name:"slack",
        bgUrl:"https://loopple.s3.eu-west-3.amazonaws.com/images/Ta8RBIBpdvmTr2zQrcArnOKUVMXwYIVX1zakLI1F.jpg",
        logo:"https://loopple.s3.eu-west-3.amazonaws.com/images/RDyzOARu35hoFaDMyHXcXJkGoDbabQizHQNsyMAL.svg",
        link:"/integrations/quickbooks"
    },
]