import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@splidejs/react-splide/css';
import '@splidejs/react-splide/css';
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.min.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ThemeContextProvider from "./contexts/ThemContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Paygeon | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeContextProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </ThemeContextProvider>
        </body>
    </html>
  );
}
